/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Component1OverridesProps = {
    Component1?: PrimitiveOverrideProps<ViewProps>;
    "Landing/Home Page"?: PrimitiveOverrideProps<ViewProps>;
    Vector125?: PrimitiveOverrideProps<IconProps>;
    Vector126?: PrimitiveOverrideProps<IconProps>;
    Vector127?: PrimitiveOverrideProps<IconProps>;
    Vector128?: PrimitiveOverrideProps<IconProps>;
    Vector129?: PrimitiveOverrideProps<IconProps>;
    Vector130?: PrimitiveOverrideProps<IconProps>;
    "Color Blur"?: PrimitiveOverrideProps<ViewProps>;
    Vector132?: PrimitiveOverrideProps<IconProps>;
    Vector133?: PrimitiveOverrideProps<IconProps>;
    "Hero Section"?: PrimitiveOverrideProps<ViewProps>;
    Img135?: PrimitiveOverrideProps<ViewProps>;
    "image 6"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 13137"?: PrimitiveOverrideProps<FlexProps>;
    "1K Peoples138"?: PrimitiveOverrideProps<FlexProps>;
    "Group 7"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 4"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 5"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 6142"?: PrimitiveOverrideProps<IconProps>;
    "Frame 8143"?: PrimitiveOverrideProps<FlexProps>;
    "1K+ Business Owners"?: PrimitiveOverrideProps<TextProps>;
    "Successfully Getting Home"?: PrimitiveOverrideProps<TextProps>;
    "1K Peoples146"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 12147"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 8148"?: PrimitiveOverrideProps<FlexProps>;
    "56 Houses"?: PrimitiveOverrideProps<TextProps>;
    "Sold Monthly"?: PrimitiveOverrideProps<TextProps>;
    "1K Peoples151"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 6152"?: PrimitiveOverrideProps<IconProps>;
    "Frame 8153"?: PrimitiveOverrideProps<FlexProps>;
    "4K+"?: PrimitiveOverrideProps<TextProps>;
    "People Looking for New Homes"?: PrimitiveOverrideProps<TextProps>;
    Navbar?: PrimitiveOverrideProps<ViewProps>;
    Logo181?: PrimitiveOverrideProps<ViewProps>;
    logo182?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 8183"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 9184"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 5"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 6"?: PrimitiveOverrideProps<FlexProps>;
    "About Us"?: PrimitiveOverrideProps<TextProps>;
    "Frame 7"?: PrimitiveOverrideProps<FlexProps>;
    reviews?: PrimitiveOverrideProps<TextProps>;
    "Frame 8190"?: PrimitiveOverrideProps<FlexProps>;
    Businesses?: PrimitiveOverrideProps<TextProps>;
    "eva:arrow-ios-forward-fill192"?: PrimitiveOverrideProps<ViewProps>;
    Vector193?: PrimitiveOverrideProps<IconProps>;
    "Frame 9"?: PrimitiveOverrideProps<FlexProps>;
    "Sign Up!"?: PrimitiveOverrideProps<TextProps>;
    "Section 2"?: PrimitiveOverrideProps<ViewProps>;
    "Featured House1111"?: PrimitiveOverrideProps<ViewProps>;
    "Featured House1112"?: PrimitiveOverrideProps<ViewProps>;
    "Featured Businesses"?: PrimitiveOverrideProps<TextProps>;
    "Group 101114"?: PrimitiveOverrideProps<ViewProps>;
    "Our Recommendation"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 141116"?: PrimitiveOverrideProps<ViewProps>;
    Category?: PrimitiveOverrideProps<FlexProps>;
    "Frame 141118"?: PrimitiveOverrideProps<FlexProps>;
    "ph:house-fill1119"?: PrimitiveOverrideProps<ViewProps>;
    Vector1120?: PrimitiveOverrideProps<IconProps>;
    Food?: PrimitiveOverrideProps<TextProps>;
    "Frame 151122"?: PrimitiveOverrideProps<FlexProps>;
    "ic:round-villa"?: PrimitiveOverrideProps<ViewProps>;
    Vector1124?: PrimitiveOverrideProps<IconProps>;
    Clothing?: PrimitiveOverrideProps<TextProps>;
    "Frame 161126"?: PrimitiveOverrideProps<FlexProps>;
    "ic:round-apartment"?: PrimitiveOverrideProps<ViewProps>;
    Vector1128?: PrimitiveOverrideProps<IconProps>;
    Beauty?: PrimitiveOverrideProps<TextProps>;
    House1130?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10"?: PrimitiveOverrideProps<FlexProps>;
    Img1132?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 151133"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 131134"?: PrimitiveOverrideProps<FlexProps>;
    "ant-design:fire-filled1135"?: PrimitiveOverrideProps<ViewProps>;
    Vector1136?: PrimitiveOverrideProps<IconProps>;
    Popular1137?: PrimitiveOverrideProps<TextProps>;
    "Nama rumah, harga1138"?: PrimitiveOverrideProps<FlexProps>;
    "Negril the Jamaican Eatery"?: PrimitiveOverrideProps<TextProps>;
    "\u2605\u2605\u2605\u2605\u26051140"?: PrimitiveOverrideProps<TextProps>;
    "Frame 131141"?: PrimitiveOverrideProps<FlexProps>;
    "Nama, Pekerjaan1142"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 61143"?: PrimitiveOverrideProps<IconProps>;
    "Frame 131144"?: PrimitiveOverrideProps<FlexProps>;
    "Dianne Russell1145"?: PrimitiveOverrideProps<TextProps>;
    "Manchester, Kentucky"?: PrimitiveOverrideProps<TextProps>;
    "Frame 11"?: PrimitiveOverrideProps<FlexProps>;
    Img1148?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 151149"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 131150"?: PrimitiveOverrideProps<FlexProps>;
    "ph:house-fill1151"?: PrimitiveOverrideProps<ViewProps>;
    Vector1152?: PrimitiveOverrideProps<IconProps>;
    "New house"?: PrimitiveOverrideProps<TextProps>;
    "Nama rumah, harga1154"?: PrimitiveOverrideProps<FlexProps>;
    "Oyamel Cocina Mexicana"?: PrimitiveOverrideProps<TextProps>;
    "\u2605\u2605\u2605\u26051156"?: PrimitiveOverrideProps<TextProps>;
    "Nama, Pekerjaan1157"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 61158"?: PrimitiveOverrideProps<IconProps>;
    "Frame 131159"?: PrimitiveOverrideProps<FlexProps>;
    "Robert Fox"?: PrimitiveOverrideProps<TextProps>;
    "Dr. San Jose, South Dakota"?: PrimitiveOverrideProps<TextProps>;
    "Frame 12"?: PrimitiveOverrideProps<FlexProps>;
    Img1163?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 151164"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 131165"?: PrimitiveOverrideProps<FlexProps>;
    "entypo:wallet"?: PrimitiveOverrideProps<ViewProps>;
    Vector1167?: PrimitiveOverrideProps<IconProps>;
    "Best Deals"?: PrimitiveOverrideProps<TextProps>;
    "Nama rumah, harga1169"?: PrimitiveOverrideProps<FlexProps>;
    "Milk and Honey"?: PrimitiveOverrideProps<TextProps>;
    "\u2605\u2605\u2605\u26051171"?: PrimitiveOverrideProps<TextProps>;
    "Nama, Pekerjaan1172"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 61173"?: PrimitiveOverrideProps<IconProps>;
    "Frame 131174"?: PrimitiveOverrideProps<FlexProps>;
    "Ronald Richards"?: PrimitiveOverrideProps<TextProps>;
    "Santa Ana, Illinois"?: PrimitiveOverrideProps<TextProps>;
    "Frame 131177"?: PrimitiveOverrideProps<FlexProps>;
    Img1178?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 151179"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 131180"?: PrimitiveOverrideProps<FlexProps>;
    "ant-design:fire-filled1181"?: PrimitiveOverrideProps<ViewProps>;
    Vector1182?: PrimitiveOverrideProps<IconProps>;
    Popular1183?: PrimitiveOverrideProps<TextProps>;
    "Nama rumah, harga1184"?: PrimitiveOverrideProps<FlexProps>;
    Anju?: PrimitiveOverrideProps<TextProps>;
    "\u2605\u2605\u2605\u2605\u26051186"?: PrimitiveOverrideProps<TextProps>;
    "Nama, Pekerjaan1187"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 61188"?: PrimitiveOverrideProps<IconProps>;
    "Frame 131189"?: PrimitiveOverrideProps<FlexProps>;
    "Jenny Wilson"?: PrimitiveOverrideProps<TextProps>;
    "Preston Rd. Inglewood, Maine 98380"?: PrimitiveOverrideProps<TextProps>;
    Arrow?: PrimitiveOverrideProps<ViewProps>;
    "Search button1193"?: PrimitiveOverrideProps<FlexProps>;
    "eva:arrow-ios-forward-fill1194"?: PrimitiveOverrideProps<ViewProps>;
    Vector1195?: PrimitiveOverrideProps<IconProps>;
    "Search button1196"?: PrimitiveOverrideProps<FlexProps>;
    "eva:arrow-ios-forward-fill1197"?: PrimitiveOverrideProps<ViewProps>;
    Vector1198?: PrimitiveOverrideProps<IconProps>;
    "Section 3"?: PrimitiveOverrideProps<ViewProps>;
    Img1200?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 17"?: PrimitiveOverrideProps<ImageProps>;
    "bi:play-circle-fill"?: PrimitiveOverrideProps<ViewProps>;
    "Vector 10"?: PrimitiveOverrideProps<IconProps>;
    Vector1204?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 18"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 191206"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ImageProps>;
    Info1208?: PrimitiveOverrideProps<ViewProps>;
    "Title, House Detail"?: PrimitiveOverrideProps<ViewProps>;
    "Featured House1210"?: PrimitiveOverrideProps<ViewProps>;
    "want to add a business?"?: PrimitiveOverrideProps<TextProps>;
    "Group 101212"?: PrimitiveOverrideProps<ViewProps>;
    "Ready to Sell!"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 141214"?: PrimitiveOverrideProps<ViewProps>;
    "Business Owners can register their business after signing up as a user and getting approved."?: PrimitiveOverrideProps<TextProps>;
    "House Detail1216"?: PrimitiveOverrideProps<ViewProps>;
    "House Detail1217"?: PrimitiveOverrideProps<TextProps>;
    "Row 1"?: PrimitiveOverrideProps<FlexProps>;
    "4 Bedrooms1219"?: PrimitiveOverrideProps<FlexProps>;
    "bed 1"?: PrimitiveOverrideProps<ViewProps>;
    Shape?: PrimitiveOverrideProps<IconProps>;
    "4 Bedrooms1222"?: PrimitiveOverrideProps<TextProps>;
    "2 Bathrooms1223"?: PrimitiveOverrideProps<FlexProps>;
    "bath 1"?: PrimitiveOverrideProps<ViewProps>;
    "Group 12"?: PrimitiveOverrideProps<ViewProps>;
    Vector1226?: PrimitiveOverrideProps<IconProps>;
    Vector1227?: PrimitiveOverrideProps<IconProps>;
    Vector1228?: PrimitiveOverrideProps<IconProps>;
    Vector1229?: PrimitiveOverrideProps<IconProps>;
    Vector1230?: PrimitiveOverrideProps<IconProps>;
    Vector1231?: PrimitiveOverrideProps<IconProps>;
    Vector1232?: PrimitiveOverrideProps<IconProps>;
    Vector1233?: PrimitiveOverrideProps<IconProps>;
    Vector1234?: PrimitiveOverrideProps<IconProps>;
    "2 Bathrooms1235"?: PrimitiveOverrideProps<TextProps>;
    "Row 2"?: PrimitiveOverrideProps<FlexProps>;
    "1 Carport1237"?: PrimitiveOverrideProps<FlexProps>;
    "car-garage 1"?: PrimitiveOverrideProps<ViewProps>;
    Group1239?: PrimitiveOverrideProps<ViewProps>;
    Group1240?: PrimitiveOverrideProps<ViewProps>;
    Vector1241?: PrimitiveOverrideProps<IconProps>;
    Vector1242?: PrimitiveOverrideProps<IconProps>;
    "1 Carport1243"?: PrimitiveOverrideProps<TextProps>;
    "2 Floors1244"?: PrimitiveOverrideProps<FlexProps>;
    "stairs-with-handrail 1"?: PrimitiveOverrideProps<ViewProps>;
    Group1246?: PrimitiveOverrideProps<ViewProps>;
    Group1247?: PrimitiveOverrideProps<ViewProps>;
    Group1248?: PrimitiveOverrideProps<ViewProps>;
    Vector1249?: PrimitiveOverrideProps<IconProps>;
    Vector1250?: PrimitiveOverrideProps<IconProps>;
    "2 Floors1251"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 191252"?: PrimitiveOverrideProps<ViewProps>;
    "Contact Info"?: PrimitiveOverrideProps<ViewProps>;
    "Group 13"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 61255"?: PrimitiveOverrideProps<IconProps>;
    "Nama, Pekerjaan1256"?: PrimitiveOverrideProps<FlexProps>;
    "Dianne Russell1257"?: PrimitiveOverrideProps<TextProps>;
    "Manager Director"?: PrimitiveOverrideProps<TextProps>;
    "Contact Now1259"?: PrimitiveOverrideProps<FlexProps>;
    "fluent:call-20-filled"?: PrimitiveOverrideProps<ViewProps>;
    Vector1261?: PrimitiveOverrideProps<IconProps>;
    "Contact Now1262"?: PrimitiveOverrideProps<TextProps>;
    "Section 4"?: PrimitiveOverrideProps<ViewProps>;
    Title1264?: PrimitiveOverrideProps<ViewProps>;
    "Customer Reviews"?: PrimitiveOverrideProps<TextProps>;
    "Group 101266"?: PrimitiveOverrideProps<ViewProps>;
    "Trending Reviews"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 141268"?: PrimitiveOverrideProps<ViewProps>;
    Review?: PrimitiveOverrideProps<FlexProps>;
    "Review 1"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 211271"?: PrimitiveOverrideProps<ViewProps>;
    "Review 1272"?: PrimitiveOverrideProps<FlexProps>;
    "Title, review1273"?: PrimitiveOverrideProps<FlexProps>;
    "My house sold out fast!"?: PrimitiveOverrideProps<TextProps>;
    "I was finally able to sell my house quickly through Hounter by immediately setting me up with people who wanted my house. I also do not get a discount from the sale of my house. Awesome!"?: PrimitiveOverrideProps<TextProps>;
    Info1276?: PrimitiveOverrideProps<FlexProps>;
    "Frame 151277"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 61278"?: PrimitiveOverrideProps<IconProps>;
    "Nama, Pekerjaan1279"?: PrimitiveOverrideProps<FlexProps>;
    "Courtney Henry1280"?: PrimitiveOverrideProps<TextProps>;
    "CEO Andarafish"?: PrimitiveOverrideProps<TextProps>;
    "Frame 151282"?: PrimitiveOverrideProps<FlexProps>;
    "bx:bxs-star1283"?: PrimitiveOverrideProps<ViewProps>;
    Vector1284?: PrimitiveOverrideProps<IconProps>;
    "4.3"?: PrimitiveOverrideProps<TextProps>;
    "Review 2"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 211287"?: PrimitiveOverrideProps<ViewProps>;
    "Review 1288"?: PrimitiveOverrideProps<FlexProps>;
    "Title, review1289"?: PrimitiveOverrideProps<FlexProps>;
    "Nadine\u2019s Hair Braiding"?: PrimitiveOverrideProps<TextProps>;
    "Nadine's Hair Braiding is truly a GAME CHANGER! I looked at my watch at 5:26 am as the 2 installers were prepping the hair. I was told \"Ma'am, you're done\" at 6:16 am. The 3.5 hours of time I got back was invaluable. Check them out, so you can look great AND save time."?: PrimitiveOverrideProps<TextProps>;
    Info1292?: PrimitiveOverrideProps<FlexProps>;
    "Frame 151293"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 61294"?: PrimitiveOverrideProps<IconProps>;
    "Nama, Pekerjaan1295"?: PrimitiveOverrideProps<FlexProps>;
    "Dianne Russell1296"?: PrimitiveOverrideProps<TextProps>;
    "Washington, D.C."?: PrimitiveOverrideProps<TextProps>;
    "Frame 151298"?: PrimitiveOverrideProps<FlexProps>;
    "bx:bxs-star1299"?: PrimitiveOverrideProps<ViewProps>;
    Vector1300?: PrimitiveOverrideProps<IconProps>;
    "4.61301"?: PrimitiveOverrideProps<TextProps>;
    "Review 3"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 211303"?: PrimitiveOverrideProps<ViewProps>;
    "Review 1304"?: PrimitiveOverrideProps<FlexProps>;
    "Title, review1305"?: PrimitiveOverrideProps<FlexProps>;
    "Buoy Collective"?: PrimitiveOverrideProps<TextProps>;
    "By looking for information about what kind of house we want, we managed to get the house we wanted very quickly, and directly connected with the seller to be able to ask about the details, very helpful!"?: PrimitiveOverrideProps<TextProps>;
    Info1308?: PrimitiveOverrideProps<FlexProps>;
    "Frame 151309"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 61310"?: PrimitiveOverrideProps<IconProps>;
    "Nama, Pekerjaan1311"?: PrimitiveOverrideProps<FlexProps>;
    "Esther Howard"?: PrimitiveOverrideProps<TextProps>;
    "Head of Marketing"?: PrimitiveOverrideProps<TextProps>;
    "Frame 151314"?: PrimitiveOverrideProps<FlexProps>;
    "bx:bxs-star1315"?: PrimitiveOverrideProps<ViewProps>;
    Vector1316?: PrimitiveOverrideProps<IconProps>;
    "4.61317"?: PrimitiveOverrideProps<TextProps>;
    Pagination?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 71319"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 81320"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 91321"?: PrimitiveOverrideProps<IconProps>;
    "Section 5"?: PrimitiveOverrideProps<ViewProps>;
    "Col 1"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 141324"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 221325"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 151326"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 171327"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 191328"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 61329"?: PrimitiveOverrideProps<IconProps>;
    "Dianne Russell1330"?: PrimitiveOverrideProps<TextProps>;
    "Secular Trends in Minority-Owned Businesses and Small Business Finance"?: PrimitiveOverrideProps<TextProps>;
    "Frame 181332"?: PrimitiveOverrideProps<FlexProps>;
    "ic:round-access-time1333"?: PrimitiveOverrideProps<ViewProps>;
    Vector1334?: PrimitiveOverrideProps<IconProps>;
    "4 min read | 25 Apr 2021"?: PrimitiveOverrideProps<TextProps>;
    "Frame 151336"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 221337"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 151338"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 171339"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 191340"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 61341"?: PrimitiveOverrideProps<IconProps>;
    "Courtney Henry1342"?: PrimitiveOverrideProps<TextProps>;
    "The Challenges in Getting Funding for Women and Minority-Owned Businesses, And How to Solve Them"?: PrimitiveOverrideProps<TextProps>;
    "Frame 181344"?: PrimitiveOverrideProps<FlexProps>;
    "ic:round-access-time1345"?: PrimitiveOverrideProps<ViewProps>;
    Vector1346?: PrimitiveOverrideProps<IconProps>;
    "6 min read | 24 Apr 2021"?: PrimitiveOverrideProps<TextProps>;
    "Frame 161348"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 221349"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 151350"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 171351"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 191352"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 61353"?: PrimitiveOverrideProps<IconProps>;
    "Darlene Robertson"?: PrimitiveOverrideProps<TextProps>;
    "First Annual MBE Advocacy Day in Prince George\u2019s County"?: PrimitiveOverrideProps<TextProps>;
    "Frame 181356"?: PrimitiveOverrideProps<FlexProps>;
    "ic:round-access-time1357"?: PrimitiveOverrideProps<ViewProps>;
    Vector1358?: PrimitiveOverrideProps<IconProps>;
    "2 min read | 24 Apr 2021"?: PrimitiveOverrideProps<TextProps>;
    "Col 2"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 23"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 171362"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 171363"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 191364"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 61365"?: PrimitiveOverrideProps<IconProps>;
    "Cameron Williamson"?: PrimitiveOverrideProps<TextProps>;
    "15 Things to Consider Before Starting a Business"?: PrimitiveOverrideProps<TextProps>;
    "Want to buy a house but are unsure about what we should know, here I will try to explain what we should know and check when we want to buy a house"?: PrimitiveOverrideProps<TextProps>;
    "Frame 181369"?: PrimitiveOverrideProps<FlexProps>;
    "ic:round-access-time1370"?: PrimitiveOverrideProps<ViewProps>;
    Vector1371?: PrimitiveOverrideProps<IconProps>;
    "8 min read | 25 Apr 2021"?: PrimitiveOverrideProps<TextProps>;
    Title1373?: PrimitiveOverrideProps<ViewProps>;
    Title1374?: PrimitiveOverrideProps<ViewProps>;
    "Need tips for Running your business? check out these articles below"?: PrimitiveOverrideProps<TextProps>;
    "Group 101376"?: PrimitiveOverrideProps<ViewProps>;
    "See tips and trick from our partnership"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 141378"?: PrimitiveOverrideProps<ViewProps>;
    "Contact Now1379"?: PrimitiveOverrideProps<FlexProps>;
    "More Articles"?: PrimitiveOverrideProps<TextProps>;
    Subscribe?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 24"?: PrimitiveOverrideProps<ImageProps>;
    "Ellipse 61383"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 71384"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 81385"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 91386"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 121387"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 25"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 27"?: PrimitiveOverrideProps<ImageProps>;
    Search?: PrimitiveOverrideProps<FlexProps>;
    "eva:email-fill"?: PrimitiveOverrideProps<ViewProps>;
    Vector1393?: PrimitiveOverrideProps<IconProps>;
    "Your email here"?: PrimitiveOverrideProps<TextProps>;
    "Search button1395"?: PrimitiveOverrideProps<FlexProps>;
    "Subsribe Now"?: PrimitiveOverrideProps<TextProps>;
    "Subscribe For More Info and update from Huemans"?: PrimitiveOverrideProps<TextProps>;
    Footer?: PrimitiveOverrideProps<ViewProps>;
    Bio?: PrimitiveOverrideProps<ViewProps>;
    "We provide information about businesses such as restaurants, salons, boutiques, and more to help people support minority-owned businesses."?: PrimitiveOverrideProps<TextProps>;
    "Frame 20"?: PrimitiveOverrideProps<FlexProps>;
    "brandico:facebook"?: PrimitiveOverrideProps<ViewProps>;
    Vector1403?: PrimitiveOverrideProps<IconProps>;
    "ant-design:twitter-outlined"?: PrimitiveOverrideProps<ViewProps>;
    Vector1405?: PrimitiveOverrideProps<IconProps>;
    "ant-design:instagram-filled"?: PrimitiveOverrideProps<ViewProps>;
    Vector1407?: PrimitiveOverrideProps<IconProps>;
    Property?: PrimitiveOverrideProps<ViewProps>;
    About?: PrimitiveOverrideProps<TextProps>;
    House1410?: PrimitiveOverrideProps<TextProps>;
    Apartment?: PrimitiveOverrideProps<TextProps>;
    Villa?: PrimitiveOverrideProps<TextProps>;
    Article1413?: PrimitiveOverrideProps<ViewProps>;
    Article1414?: PrimitiveOverrideProps<TextProps>;
    "New Article"?: PrimitiveOverrideProps<TextProps>;
    "Popular Article"?: PrimitiveOverrideProps<TextProps>;
    "Tips & Tricks"?: PrimitiveOverrideProps<TextProps>;
    "Most Read"?: PrimitiveOverrideProps<TextProps>;
    Contact1419?: PrimitiveOverrideProps<ViewProps>;
    Contact1420?: PrimitiveOverrideProps<TextProps>;
    "2464 Royal Ln. Mesa, New Jersey 45463"?: PrimitiveOverrideProps<TextProps>;
    "(671) 555-0110"?: PrimitiveOverrideProps<TextProps>;
    "info@hounter.com"?: PrimitiveOverrideProps<TextProps>;
    Logo1424?: PrimitiveOverrideProps<ViewProps>;
    logo1425?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 81426"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 91427"?: PrimitiveOverrideProps<ViewProps>;
    "Hueman Logo 2"?: PrimitiveOverrideProps<ImageProps>;
    "Hueman Logo 1"?: PrimitiveOverrideProps<ImageProps>;
} & EscapeHatchProps;
export declare type Component1Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: Component1OverridesProps | undefined | null;
}>;
export default function Component1(props: Component1Props): React.ReactElement;
